extends:
  - airbnb
parser: babel-eslint
plugins:
  - prettier
rules:
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  arrow-parens: 0
  implicit-arrow-linebreak: 0
  no-console: 0
  no-underscore-dangle: 0
  react/jsx-filename-extension: 0
  import/no-extraneous-dependencies: 0
  react/jsx-indent:
    - 1
    - 4
  react/jsx-indent-props:
    - 1
    - 4
  indent:
    - 2
    - 4
globals:
  localStorage: true
  __DEV__: true
env:
  browser: true
  # node: true
  # jasmine: true
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    env:
      jest: true
      mocha: true
